---
# tasks file for fastapi
- name: Clone the FastAPI repository
  ansible.builtin.git:
    repo: "https://github.com/antonblaise/dockerized-fastapi-devops.git"
    dest: "{{ fastapi_repo_path }}"
    version: main

- name: Build and run the containers
  become: yes
  ansible.builtin.command:
    cmd: docker compose up -d --build
    chdir: "{{ fastapi_repo_path }}"
  register: compose_result
  failed_when: 
    - compose_result.rc != 0
    - '"Already up-to-date" not in compose_result.stderr'