name: docker-build
run-name: Build Docker image and test FastAPI endpoint
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v6
      - name: Build Docker image
        run: docker compose up --build -d
      - name: Check running containers
        run: docker ps
      - name: Test FastAPI endpoint
        run: curl http://localhost:8000/docs | grep "Swagger UI"
