name: docker-build
run-name: Build Docker image and test FastAPI endpoint
on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v6
      - name: Build Docker image
        run: docker compose up --build -d
      - name: Check running containers
        run: |
          docker ps | grep "postgres-db"
          docker ps | grep "fastapi-app"
      - name: Test FastAPI endpoint
        run: |
          for i in {1..10}; do
            echo "Attempt $i ..."

            if curl -s http://localhost:8000/docs | grep "Swagger UI"; then
              echo "FastAPI is ready!"
              exit 0
            fi

            sleep 3
          done

          echo "FastAPI did not become ready in time."
          exit 1
